version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
      - dashboard/.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-faivor}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./dashboard:/app
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - dashboard/.env
    environment:
      - NODE_ENV=production
    command: sh -c "bun install && DATABASE_URL='postgres://postgres:postgres@postgres:5432/faivor' bunx node-pg-migrate up && bun run build && cd build && bun run start"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
