services:
  postgres:
    image: postgres:latest
    env_file:
      - dashboard/.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-faivor}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dashboard/seed-database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./dashboard:/app
    ports:
      - "5173:5173"
    env_file:
      - dashboard/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    # command: sh -c "bun install && bun run migrate:dev up && bun run dev"
    command: sh -c "bun install && DATABASE_URL='postgres://postgres:postgres@postgres:5432/faivor' bunx node-pg-migrate up && bun run dev"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  seed:
    image: postgres:latest
    env_file:
      - dashboard/.env
    environment:
      PGPASSWORD: ${DB_PASSWORD:-postgres}
    command: psql -h postgres -U ${DB_USER:-postgres} -d ${DB_NAME:-faivor} -f /seed-database/seed.sql
    volumes:
      - ./dashboard/seed-database:/seed-database
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
